backend:
  name: github
  repo: DumitritaZ/fussioncomm-ict   # înlocuiește cu userul tău
  branch: main
  base_url: hhttps://fussioncomm-ict.onrender.com
  auth_endpoint: /auth


media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "company"
    label: "Setări companie"
    files:
      - file: "content/company.json"
        label: "Date companie"
        name: "company"
        format: "json"
        fields:
          - {label: "Nume", name: "name", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Locație", name: "location", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - label: "Hero (Acasă)"
            name: "home"
            widget: "object"
            fields:
              - {label: "H1", name: "h1", widget: "string"}
              - {label: "Lead", name: "lead", widget: "text"}
              - {label: "Bullets", name: "bullets", widget: "list", field: {label: "Punct", name: "item", widget: "string"}}

  - name: "services"
    label: "Servicii"
    files:
      - file: "content/services.json"
        label: "Lista servicii"
        name: "services"
        format: "json"
        fields:
          - label: "Servicii"
            name: "items"
            widget: "list"
            fields:
              - {label: "Titlu", name: "title", widget: "string"}
              - {label: "Descriere", name: "description", widget: "text"}
              - {label: "Bullets", name: "bullets", widget: "list", field: {label: "Punct", name: "item", widget: "string"}}

  - name: "projects"
    label: "Proiecte"
    files:
      - file: "content/projects.json"
        label: "Lista proiecte"
        name: "projects"
        format: "json"
        fields:
          - label: "Proiecte"
            name: "items"
            widget: "list"
            fields:
              - {label: "Titlu", name: "title", widget: "string"}
              - {label: "Rezumat", name: "summary", widget: "text"}
              - {label: "Imagine (opțional)", name: "image", widget: "image", required: false}
